### ISSUE TITLE
Convertion to FLAC doesn't happen

### ISSUE THREAD

**Issue by g60jet** [tattwamasi/TeslaTunes#11]
Hi,

I've install and ran the software but it fails to convert any files.

it copies all the files from my network drive to a dedicated USB HDD to go into my Tesla, but the m4a files are just copied not converted.

i've tried scanning first, then copy convert.  Nothing seems to convert the apple files to any other files format.

Am I missing something?

**Comment by tattwamasi** [comment]
Are the m4a files apple lossless files?  The .m4a extension is also used for the AAC audio files more commonly found from iTunes, etc. The Tesla will play AAC just fine and converting them to flac would just waste time and space.

**Comment by lraesly** [comment]
tattwamasi,

(This is majorlance from the teslamotorclub forums).  Now that 8.0 can show embedded cover art, is there a way to force the apple lossless to Flac conversion to include imbedded cover art?  

I noticed after the 8.0 update that many of my files were using the embedded cover art but my apple lossless to Flac files weren't showing anything.  I'm still a little confused on what is going on (was told on the forums that this was covered in the 53 page and counting bug list for 8.0).

Thoughts?

Lee

**Comment by tattwamasi** [comment]
I'll look into it.  I thought I copied any metadata that was in the apple lossless over to the Flac file, but I never specifically looked at or tested album art since it wasn't used anyway.  

Separate issue than this though (in fact is #10)

**Comment by tattwamasi** [comment]
Closing this issue soon due to no follow up.  Hopefully was just a misunderstanding and things are squared away.  If not, @g60jet please update the issue with what type of files they are and what you think should be happening

**Comment by tattwamasi** [comment]
Closing since I've received no further info from the original poster.  If there are more questions or feedback on this issue, feel free to post again.
