### ISSUE TITLE
Add(ed) "ignore missing tracks" 

### ISSUE THREAD

**Issue by headcrash13** [tattwamasi/TeslaTunes#12]
Added "Ignore Missing Tracks" when a track's location isn’t found - It will skip over any missing tracks until the next playlist is processed (which will return to notifying you when a track can't be found).

I added this feature (locally), as I wanted a way to continue processing when tracks were "missing" (mainly Apple Music / iCloud tracks) without having to keep clicking the "Skip" button over and over and over again.

(I couldn't make a pull request, so here's the changes from the latest master branch)

The (minor) changes are to CopyConvertDirs.mm:

[CopyConvertDirs.mm](https://dl.dropboxusercontent.com/u/19675079/CopyConvertDirs.mm)

**Comment by tattwamasi** [comment]
Cool. Sounds like a good thing to add.  Wonder why pull request wouldn't work.

**Comment by tattwamasi** [comment]
Looks straightforward and is a nice idea.

Why the comment, ` continue; // Unnecessary, but keeping consistant with the line above.`   ?

**Comment by headcrash13** [comment]
I'm not authorized to pull request for this repo. :)

The "continue" and the comment were just to be consistent with the "continue" you had on the line above. However, since there's no code following either continue statement, they're unnecessary (the loop will continue to the next iteration right after, anyway).

**Comment by tattwamasi** [comment]
Check the loop body again. There's lots of code following.  The if check is to go to the next iteration or return altogether if a location is bad. If no continue was there you'd proceed through the rest of the for loop body and try the copy, etc.

I've never done anything to set up and allow or disallow pull requests.  Will have to investigate I guess. 

I really appreciate the contribution.  It's that great combination of simple and high value.

**Comment by richtong** [comment]
Oh, I see, so this only works on locally stored music? Might want to be in the README.md
