### ISSUE TITLE
missing tag.framework

### ISSUE THREAD

**Issue by tampamacdev** [tattwamasi/TeslaTunes#16]
Hi, I would like to build TeslaTunes from your source code, but the project is missing the tag.framework bundle. Is this framework part of another github repo? If so, what is the name of the github repo? If not, can you provide the source code for lib.framework? I'm assuming it's similar to the TagLib.framework repo on github. 

Thanks,

Ben

**Comment by tattwamasi** [comment]
The framework is the taglib framework. You’ll have to grab it and build it yourself if you don’t want the version in the repo.  I should have set the frameworks up as submodules or something to begin with,  but there are no changes to to their code.  The latest versions are using the taglib2 branch.

**Comment by tampamacdev** [comment]
I tried "decarbonization/TagLib" and it doesn't have the headers you are including. I also tried "rrooding/TagLib.framework" and I'm getting build errors. Did you build the framework from source by going to "http://developer.kde.org/~wheeler/taglib.html" and downloading one of their versions?

**Comment by tattwamasi** [comment]
I used the github taglib.orb repo.  See taglib.orb for more info, and you can grab the repo from https://github.com/taglib/taglib

My guess is that you weren’t on the taglib2 branch of the repo, if you were using a repo vs. the tar distros.  Otherwise, not sure what you are seeing

**Comment by tampamacdev** [comment]
Thanks for the link. 

For anyone reading this "issue" thread, all I had to do to build the framework was:

1. git clone https://github.com/taglib/taglib
2. download cmake 
3. edit the "CMakeList.txt" file to turn on BUILD_FRAMEWORK
    _option(BUILD_FRAMEWORK "Build an OS X framework" ON)_
4. run the command "cmake -G Xcode" inside the "taglib" directory 
5. open the taglib.xcodeproj in Xcode and build

**Comment by tattwamasi** [comment]
Cool, glad you got it going. Closing issue now.
