### ISSUE TITLE
Feature request: bandwidth limited compression

### ISSUE THREAD

**Issue by clgood** [tattwamasi/TeslaTunes#9]
Apologies in advance if this isn't the right way to make a feature request. I don't have much experience on GitHub.

This program is wonderful, and _so_ close to what I want. Since high fidelity in a car is like Arpege in a glue factory, I don't care if the files I play there are lossless. I _do_ want to be able to carry more of my rather large music collection. When I sync to my iPhone I check the box to limit the bitrate to 128K. I really wish I could tell TeslaTunes to do the same. I wouldn't care if the results were .flac or .mp3, as long as the Tesla could read it.

Thanks for this program in any case.

**Comment by tattwamasi** [comment]
This is a great way to make a feature request.  Thanks for the feedback and suggestion. 

I hadn't considered it, but It's a reasonable and interesting feature to add.  I'll keep it in mind if/when I ever get into the code again.  I have to warn you though, that I haven't been planning to do so anytime soon, and that you may be better off either just going ahead and buying more cheap flash or a portable HD (2TB for $80 for seagate bus powered USB3 drive, for example), or using another program to do what you are looking for (particularly if you don't have the naming issues, playlists, genre/tag issues, etc. that are part of this util).

**Comment by tattwamasi** [comment]
I'm going to go ahead and close this one as a will not fix.  I think it's a reasonable feature to have, but balanced against the other things I should be doing with my time and the price of storage, just don't see it ever working its way up to actually being implemented - at least by me.
